[azure]
openai_api_base = https://dmow-snd-hs-mediaanopenai-oai.openai.azure.com/
#openai_api_version = 2025-02-01-preview
openai_api_version = 2025-04-01-preview
#deployment_name = SanderMaze-o1
#deployment_name = Sander-GPT-4o
deployment_name = gpt-5.4
cognitive_services_url = https://mediaan-documentintelligence.cognitiveservices.azure.com/