basis = "General information of the invoice."
currency = "the currency in which all the prices are issued. Don't use currency symbol. Write the full name."
documentNumber = "a unique identifier or reference for the quotation."
documentDate = "the date at which the quotation was issued or sent."
items = "List of ordered, supplied, delivered or picked up goods or services."
raw= "the full received text. No alterations additions or exclusions are done to this."
totalCount = "empty field"