on:
  workflow_call:
    secrets:
      azure-cognitive-service-key:
        required: true
      openai-api-key:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with coverage
      env:
        AZURE_COGS_KEY: ${{ secrets.azure-cognitive-service-key }}
        OPENAI_API_KEY: ${{ secrets.openai-api-key }}
      run: |
        coverage run -m pytest
        coverage xml

    - name: Upload Coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage
        path: coverage.xml
        retention-days: 7
