name: Release

on:
  workflow_dispatch:
    inputs:
      scope:
        type: choice
        description: Scope of release
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.release_tag.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tag next semantic version
        id: release_tag
        uses: zwaldowski/semver-release-action@v4
        with:
          bump: ${{ github.event.inputs.scope }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          per_branch: true
          prefix: v

  docker:
    needs: release
    uses: ./.github/workflows/docker.yml
    with:
      image-name: ${{ github.event.repository.name }}
      tags: "[ '${{ needs.release.outputs.version}}' ]"
      target: ${{ vars.TARGET }}
    secrets:
      docker-registry-username: ${{ secrets.HARBOR_USERNAME }}
      docker-registry-password: ${{ secrets.HARBOR_PASSWORD }}
